# Site settings
title: Autoscuola San Benedetto
email: your-email@domain.com
url: https://github.com/jeromelachaud/freelancer-theme
description: "Autoscuola San Benedetto offre corsi di guida teorici e pratici per tutte le patenti in Italia. Esperienza di oltre 40 anni per una formazione sicura e professionale."
keywords: "Autoscuola, Cassino, Autoscuola San Benedetto, Patente B, Esame di Guida, Patente A, Driving License Italy, 
            Autoscuola San Benedetto, Scuola guida San Benedetto, Patente di guida Italia, Corsi di guida sicura, 
            Lezioni di guida pratica, Esame patente teoria e pratica"
skills: "Driving School - Driving Theory Lessons - Driving Practical Lessons"
meta_author: LastName FirstName

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Nagesh Kommuri
  location: Location
  social: Around the Web

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  # - title: twitter
  #   url: http://twitter.com/jekyllrb
  - title: facebook
    url: https://www.facebook.com/p/Autoscuola-San-Benedetto-100069163785912/?locale=it_IT
  # - title: stack-overflow
  #   url: http://stackoverflow.com/questions/tagged/jekyll
  # - title: bitbucket
  #   url: http://bitbucket.org/jekyll
  # - title: github
  #   url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: Via Arigni, 86, 03043
  - line: Cassino (FR) 

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
